import { createFileRoute } from "@tanstack/react-router";
import { Building2, Factory, Home, Ruler, Hammer, ClipboardCheck } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { CTA, NumberedSteps, PageHero, SectionIntro, images } from "@/components/site/Site";
export const Route=createFileRoute("/costruzioni")({head:()=>({meta:[{title:"Costruzioni — SRAGROUP"},{name:"description",content:"Costruzioni industriali, commerciali e residenziali chiavi in mano."},{property:"og:title",content:"Costruzioni — SRAGROUP"},{property:"og:description",content:"General contractor per opere complesse, affidabili e puntuali."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Page});
const sectors: [LucideIcon,string,string][]=[[Factory,"Industriale","Stabilimenti produttivi, hub logistici e riqualificazioni."],[Building2,"Commerciale","Spazi retail e direzionali ad alta efficienza."],[Home,"Residenziale","Complessi contemporanei, confortevoli e sostenibili."]];
const services: [LucideIcon,string][]=[[Ruler,"Progettazione integrata"],[Hammer,"General contracting"],[ClipboardCheck,"Direzione lavori"],[Factory,"Prefabbricati e strutture"],[Building2,"Riqualificazione"],[Home,"Manutenzione programmata"]];
const steps=[{title:"Analisi",text:"Obiettivi, vincoli e fattibilità."},{title:"Progetto",text:"Coordinamento tecnico integrato."},{title:"Pianificazione",text:"Tempi, costi e forniture."},{title:"Esecuzione",text:"Gestione diretta del cantiere."},{title:"Consegna",text:"Collaudo e assistenza finale."}];
function Page(){return <><PageHero eyebrow="Divisione Costruzioni" title="Costruiamo certezze." text="Dalla progettazione alla consegna, coordiniamo persone, competenze e risorse per realizzare opere complesse senza compromessi." image={images.constructionHero} tone="construction"/><section className="site-container py-24"><SectionIntro eyebrow="Ambiti" title="Competenza trasversale, controllo verticale." tone="construction"/><div className="mt-12 grid gap-5 md:grid-cols-3">{sectors.map(([Icon,title,text])=><article key={title} className="border-t-2 border-construction bg-card p-7"><Icon className="size-7 text-construction"/><h3 className="mt-16 text-2xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div></section><section className="bg-charcoal py-24 text-offwhite"><div className="site-container"><SectionIntro eyebrow="Servizi" title="Un unico interlocutore per l’intero processo." tone="construction"/><div className="mt-14 grid gap-px bg-offwhite/10 sm:grid-cols-2 lg:grid-cols-3">{services.map(([Icon,t])=><div key={t} className="bg-charcoal p-7"><Icon className="size-6 text-construction"/><h3 className="mt-10 text-lg font-semibold">{t}</h3></div>)}</div></div></section><section className="site-container py-24"><SectionIntro eyebrow="Metodo" title="Cinque fasi, un controllo costante." tone="construction"/><div className="mt-12"><NumberedSteps items={steps}/></div></section><CTA tone="construction" title="Il vostro progetto merita basi solide."/></>}
