/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CostruzioniRouteImport } from './routes/costruzioni'
import { Route as FotovoltaicoRouteImport } from './routes/fotovoltaico'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as EnConstructionRouteImport } from './routes/en/construction'
import { Route as EnContactRouteImport } from './routes/en/contact'
import { Route as EnCookiePolicyRouteImport } from './routes/en/cookie-policy'
import { Route as EnPrivacyPolicyRouteImport } from './routes/en/privacy-policy'
import { Route as EnSolarRouteImport } from './routes/en/solar'
import { Route as ProgettiIndexRouteImport } from './routes/progetti/index'
import { Route as ProgettiSlugRouteImport } from './routes/progetti/$slug'
import { Route as EnProjectsIndexRouteImport } from './routes/en/projects/index'
import { Route as EnProjectsSlugRouteImport } from './routes/en/projects/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CostruzioniRoute = CostruzioniRouteImport.update({
  id: '/costruzioni',
  path: '/costruzioni',
  getParentRoute: () => rootRouteImport,
} as any)
const FotovoltaicoRoute = FotovoltaicoRouteImport.update({
  id: '/fotovoltaico',
  path: '/fotovoltaico',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EnConstructionRoute = EnConstructionRouteImport.update({
  id: '/en/construction',
  path: '/en/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCookiePolicyRoute = EnCookiePolicyRouteImport.update({
  id: '/en/cookie-policy',
  path: '/en/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPrivacyPolicyRoute = EnPrivacyPolicyRouteImport.update({
  id: '/en/privacy-policy',
  path: '/en/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSolarRoute = EnSolarRouteImport.update({
  id: '/en/solar',
  path: '/en/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettiIndexRoute = ProgettiIndexRouteImport.update({
  id: '/progetti/',
  path: '/progetti/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettiSlugRoute = ProgettiSlugRouteImport.update({
  id: '/progetti/$slug',
  path: '/progetti/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsIndexRoute = EnProjectsIndexRouteImport.update({
  id: '/en/projects/',
  path: '/en/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnProjectsSlugRoute = EnProjectsSlugRouteImport.update({
  id: '/en/projects/$slug',
  path: '/en/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/costruzioni': typeof CostruzioniRoute
  '/fotovoltaico': typeof FotovoltaicoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/en/about': typeof EnAboutRoute
  '/en/construction': typeof EnConstructionRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookie-policy': typeof EnCookiePolicyRoute
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/solar': typeof EnSolarRoute
  '/progetti/$slug': typeof ProgettiSlugRoute
  '/en/': typeof EnIndexRoute
  '/progetti/': typeof ProgettiIndexRoute
  '/en/projects/$slug': typeof EnProjectsSlugRoute
  '/en/projects/': typeof EnProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/costruzioni': typeof CostruzioniRoute
  '/fotovoltaico': typeof FotovoltaicoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/en/about': typeof EnAboutRoute
  '/en/construction': typeof EnConstructionRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookie-policy': typeof EnCookiePolicyRoute
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/solar': typeof EnSolarRoute
  '/progetti/$slug': typeof ProgettiSlugRoute
  '/en': typeof EnIndexRoute
  '/progetti': typeof ProgettiIndexRoute
  '/en/projects/$slug': typeof EnProjectsSlugRoute
  '/en/projects': typeof EnProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/costruzioni': typeof CostruzioniRoute
  '/fotovoltaico': typeof FotovoltaicoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/en/about': typeof EnAboutRoute
  '/en/construction': typeof EnConstructionRoute
  '/en/contact': typeof EnContactRoute
  '/en/cookie-policy': typeof EnCookiePolicyRoute
  '/en/privacy-policy': typeof EnPrivacyPolicyRoute
  '/en/solar': typeof EnSolarRoute
  '/progetti/$slug': typeof ProgettiSlugRoute
  '/en/': typeof EnIndexRoute
  '/progetti/': typeof ProgettiIndexRoute
  '/en/projects/$slug': typeof EnProjectsSlugRoute
  '/en/projects/': typeof EnProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/costruzioni'
    | '/fotovoltaico'
    | '/privacy-policy'
    | '/en/about'
    | '/en/construction'
    | '/en/contact'
    | '/en/cookie-policy'
    | '/en/privacy-policy'
    | '/en/solar'
    | '/progetti/$slug'
    | '/en/'
    | '/progetti/'
    | '/en/projects/$slug'
    | '/en/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/costruzioni'
    | '/fotovoltaico'
    | '/privacy-policy'
    | '/en/about'
    | '/en/construction'
    | '/en/contact'
    | '/en/cookie-policy'
    | '/en/privacy-policy'
    | '/en/solar'
    | '/progetti/$slug'
    | '/en'
    | '/progetti'
    | '/en/projects/$slug'
    | '/en/projects'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/costruzioni'
    | '/fotovoltaico'
    | '/privacy-policy'
    | '/en/about'
    | '/en/construction'
    | '/en/contact'
    | '/en/cookie-policy'
    | '/en/privacy-policy'
    | '/en/solar'
    | '/progetti/$slug'
    | '/en/'
    | '/progetti/'
    | '/en/projects/$slug'
    | '/en/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  CostruzioniRoute: typeof CostruzioniRoute
  FotovoltaicoRoute: typeof FotovoltaicoRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  EnAboutRoute: typeof EnAboutRoute
  EnConstructionRoute: typeof EnConstructionRoute
  EnContactRoute: typeof EnContactRoute
  EnCookiePolicyRoute: typeof EnCookiePolicyRoute
  EnPrivacyPolicyRoute: typeof EnPrivacyPolicyRoute
  EnSolarRoute: typeof EnSolarRoute
  ProgettiSlugRoute: typeof ProgettiSlugRoute
  EnIndexRoute: typeof EnIndexRoute
  ProgettiIndexRoute: typeof ProgettiIndexRoute
  EnProjectsSlugRoute: typeof EnProjectsSlugRoute
  EnProjectsIndexRoute: typeof EnProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/costruzioni': {
      id: '/costruzioni'
      path: '/costruzioni'
      fullPath: '/costruzioni'
      preLoaderRoute: typeof CostruzioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotovoltaico': {
      id: '/fotovoltaico'
      path: '/fotovoltaico'
      fullPath: '/fotovoltaico'
      preLoaderRoute: typeof FotovoltaicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/construction': {
      id: '/en/construction'
      path: '/en/construction'
      fullPath: '/en/construction'
      preLoaderRoute: typeof EnConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/cookie-policy': {
      id: '/en/cookie-policy'
      path: '/en/cookie-policy'
      fullPath: '/en/cookie-policy'
      preLoaderRoute: typeof EnCookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/privacy-policy': {
      id: '/en/privacy-policy'
      path: '/en/privacy-policy'
      fullPath: '/en/privacy-policy'
      preLoaderRoute: typeof EnPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/solar': {
      id: '/en/solar'
      path: '/en/solar'
      fullPath: '/en/solar'
      preLoaderRoute: typeof EnSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progetti/': {
      id: '/progetti/'
      path: '/progetti'
      fullPath: '/progetti/'
      preLoaderRoute: typeof ProgettiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progetti/$slug': {
      id: '/progetti/$slug'
      path: '/progetti/$slug'
      fullPath: '/progetti/$slug'
      preLoaderRoute: typeof ProgettiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/': {
      id: '/en/projects/'
      path: '/en/projects'
      fullPath: '/en/projects/'
      preLoaderRoute: typeof EnProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/projects/$slug': {
      id: '/en/projects/$slug'
      path: '/en/projects/$slug'
      fullPath: '/en/projects/$slug'
      preLoaderRoute: typeof EnProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  CostruzioniRoute: CostruzioniRoute,
  FotovoltaicoRoute: FotovoltaicoRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  EnAboutRoute: EnAboutRoute,
  EnConstructionRoute: EnConstructionRoute,
  EnContactRoute: EnContactRoute,
  EnCookiePolicyRoute: EnCookiePolicyRoute,
  EnPrivacyPolicyRoute: EnPrivacyPolicyRoute,
  EnSolarRoute: EnSolarRoute,
  ProgettiSlugRoute: ProgettiSlugRoute,
  EnIndexRoute: EnIndexRoute,
  ProgettiIndexRoute: ProgettiIndexRoute,
  EnProjectsSlugRoute: EnProjectsSlugRoute,
  EnProjectsIndexRoute: EnProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
